[pytest]
pythonpath = .
; pythonpath 
addopts = -v -s --tb=short --disable-warnings


; ĐẶT ';' TRƯỚC CÁC CÂU COMMENTS

; Các tùy chọn trong addopts: options bổ sung khi chạy pytest. (pytest -v)
; -v: Hiển thị tên chi tiết từng bài test.
; -s: Cho phép hiển thị log print() ra màn hình terminal.
; --tb=short: Hiển thị báo cáo lỗi ngắn gọn khi test bị gãy (failed).
; --disable-warnings: Tắt warnings summary khi chạy pytest.